### ISSUE TITLE
Upgrade to App Insights 2.15.0

### ISSUE THREAD

**Issue by RiverPhillips** [serilog-contrib/serilog-sinks-applicationinsights#147]
App Insights 2.15.0 has been released with several bug fixes and improvements. 
App Insights now only supports .NET 4.5.2, .NET 4.6.2 and .NET Standard.

I propose upgrading Serilog Sinks ApplicationInsights to those supported versions and upgrading to App Insights 2.15.0

**Comment by NickMSW** [comment]
Is there any update on this one? App Insights is now at version 2.17.0.

**Comment by nblumhardt** [comment]
We're in the process of getting new maintainers on board :-) if you're able to lend a hand, there's a new open issue tracking v4.0 where we're collecting tasks that need attention. Cheers!
