### ISSUE TITLE
dotnetcore - AI Sink not respecting levelSwitch

### ISSUE THREAD

**Issue by devarshad** [serilog-contrib/serilog-sinks-applicationinsights#149]
I'm using dotnet core 3.1 and Serilog AI Sink 3.1 with serilog-setting package to update logging level dynamically with following config setting:

  `"Serilog": {
    "LevelSwitches": {
      "$consoleSwitch": "Warning",
      "$aiSwitch": "Information"
    },
    "Using": [
      "Serilog.Sinks.Async",
      "Serilog.Sinks.ApplicationInsights"
    ],
    "IncludeScopes": false,
    "MinimumLevel": {
      "Default": "Information",
      "Override": {
        "Microsoft": "Warning",
        "System": "Warning",
        "ServiceProfiler": "Error"
      }
    },
    "WriteTo": [
      {
        "Name": "Async",
        "Args": {
          "configure": [
            {
              "Name": "Console",
              "Args": {
                "levelSwitch": "$consoleSwitch",
                "outputTemplate": "{Timestamp:HH:mm:ss.fff} sev={Level:u3} app={Application} host={MachineName} pid={ProcessId} thread={ThreadId} ip={ClientIp} user={UserId} loc={Locale} tx={TransId} event={LoggingEvent} | {Message}{NewLine}{Exception}"
              }
            },
            {
              "Name": "ApplicationInsights",
              "Args": {
                "levelSwitch": "$consoleSwitch",
                "telemetryConverter": "Serilog.Sinks.ApplicationInsights.Sinks.ApplicationInsights.TelemetryConverters.EventTelemetryConverter, Serilog.Sinks.ApplicationInsights"
              }
            }
          ]
        }
      }
    ],
    "Enrich": [
      "FromLogContext",
      "WithMachineName",
      "WithThreadId",
      "WithProcessId"
    ],
    "Properties": {
      "Application": "ApiTest"
    }
  }`

Console switch is working as expected but the AI sink is not working and only the default logging level is being picked up.

Any quick solution is highly appreciated.

**Comment by jotabe-net** [comment]
If you try to configrue this in code, instead of in the JSON file, you'll realize that there is no `levelSwitch` parameter in the sink's configuration methods. So, that parameter is completely ignore.

I created [pull request 159](https://github.com/serilog/serilog-sinks-applicationinsights/pull/159) that includes and uses the missing parameter.
