### ISSUE TITLE
Serilog not using Periodic Batching from web application to Azure AppInsights  causing huge response time / performance issues with the website

### ISSUE THREAD

**Issue by porsivasu** [serilog-contrib/serilog-sinks-applicationinsights#151]
Serilog not using Periodic Batching from web application to Azure AppInsights  causing huge response time / performance issues with the website.

**Comment by nblumhardt** [comment]
Hi! Thanks for the note; if you have any measurements or investigations that illustrate this, a proposal or PR would be welcome. See also _Serilog.Sinks.Async_, not sure if this is an exact fit but may reduce latency if the telemetry client starts blocking for some reason. Closing as stale for the time being.
