### ISSUE TITLE
Cloud Role Name is missing after upgrading to latest stable version of Microsoft.ApplicationInsights.AspNetCore

### ISSUE THREAD

**Issue by NitinM3** [serilog-contrib/serilog-sinks-applicationinsights#152]
Recently I upgraded to latest stable version of Microsoft.ApplicationInsights.AspNetCore [(2.1.16)](https://www.nuget.org/packages/Microsoft.ApplicationInsights.AspNetCore) and `cloud_RoleName` started disappearing from Application Insights Traces. ( see [2147)](https://github.com/microsoft/ApplicationInsights-dotnet/issues/2147) for more details)

Serilog Packages used:
 - Serilog.AspNetCore [(3.4.0)](https://www.nuget.org/packages/Serilog.AspNetCore/)
 - Serilog.Sinks.ApplicationInsights [(3.1.0)](https://www.nuget.org/packages/Serilog.Sinks.ApplicationInsights/)

Below are the samples which will help to reproduce the issue.

[With Serilog.zip](https://github.com/serilog/serilog-sinks-applicationinsights/files/5794140/With.Serilog.zip)
[Without Serilog (working).zip](https://github.com/serilog/serilog-sinks-applicationinsights/files/5794243/Without.Serilog.working.zip)

**Comment by daniel-simpson** [comment]
Not sure if it will help, but I had a similar issue which I "fixed" (patched in a most hacky way) by creating an overridden `TraceTelemetryInitializer` and using that when setting up my App Insights sink.  I also couldn't live without my custom cloud_roleName!

**SerilogAppInsightsTraceTelemetryConverter.cs**
```csharp
using Microsoft.ApplicationInsights.Channel;
using Serilog.Events;
using Serilog.Sinks.ApplicationInsights.Sinks.ApplicationInsights.TelemetryConverters;
using System;
using System.Collections.Generic;
using System.Reflection;

namespace MyApp.Common.Logging.TelemetryConverters
{
    public class SerilogAppInsightsTraceTelemetryConverter : TraceTelemetryConverter
    {
        private string? _roleName;

        public SerilogAppInsightsTraceTelemetryConverter()
        {
            _roleName = Assembly.GetEntryAssembly()?.GetName()?.Name;  // Or whatever else you'd like to set the name to.
        }

        public override IEnumerable<ITelemetry> Convert(LogEvent logEvent, IFormatProvider formatProvider)
        {
            foreach(var telemetry in base.Convert(logEvent, formatProvider))
            {
                telemetry.Context.Cloud.RoleName = _roleName;
                yield return telemetry;
            }
        }
    }
}
```

Then use it during startup:
```csharp
Host.CreateDefaultBuilder(args)
    .UseSerilog((context, services, serilogConfiguration) =>
        serilogConfiguration.WriteTo.ApplicationInsights(new TelemetryConfiguration(instrumentationKey), new SerilogAppInsightsTraceTelemetryConverter(), LogEventLevel.Information);
    )
```

**Comment by NitinM3** [comment]
> Not sure if it will help, but I had a similar issue which I "fixed" (patched in a most hacky way) by creating an overridden `TraceTelemetryInitializer` and using that when setting up my App Insights sink. I also couldn't live without my custom cloud_roleName!
> 
> **SerilogAppInsightsTraceTelemetryConverter.cs**
> 
> ```cs
> using Microsoft.ApplicationInsights.Channel;
> using Serilog.Events;
> using Serilog.Sinks.ApplicationInsights.Sinks.ApplicationInsights.TelemetryConverters;
> using System;
> using System.Collections.Generic;
> using System.Reflection;
> 
> namespace MyApp.Common.Logging.TelemetryConverters
> {
>     public class SerilogAppInsightsTraceTelemetryConverter : TraceTelemetryConverter
>     {
>         private string? _roleName;
> 
>         public SerilogAppInsightsTraceTelemetryConverter()
>         {
>             _roleName = Assembly.GetEntryAssembly()?.GetName()?.Name;  // Or whatever else you'd like to set the name to.
>         }
> 
>         public override IEnumerable<ITelemetry> Convert(LogEvent logEvent, IFormatProvider formatProvider)
>         {
>             foreach(var telemetry in base.Convert(logEvent, formatProvider))
>             {
>                 telemetry.Context.Cloud.RoleName = _roleName;
>                 yield return telemetry;
>             }
>         }
>     }
> }
> ```
> 
> Then use it during startup:
> 
> ```cs
> Host.CreateDefaultBuilder(args)
>     .UseSerilog((context, services, serilogConfiguration) =>
>         serilogConfiguration.WriteTo.ApplicationInsights(new TelemetryConfiguration(instrumentationKey), new SerilogAppInsightsTraceTelemetryConverter(), LogEventLevel.Information);
>     )
> ```

@daniel-simpson Thanks. This workaround worked for me as well.

**Comment by alexeymarkov** [comment]
Are there any news? When it is going to be fixed?

**Comment by AAimson** [comment]
Snap

**Comment by nblumhardt** [comment]
Hi! It's uncertain whether this is a bug or if it's an App Insights change; any deeper investigation/proposals would be welcome. Closing as stale for now. Thanks!

**Comment by meixger** [comment]
I check for the presence of  a App Service Kudo header **WAS-DEFAULT-HOSTNAME** like Microsoft.ApplicationInsights.AspNetCore does, store the value in a static RoleNameContainer and use it in a TraceTelemetryConverter.

[source of RoleNameContainer from Microsoft.ApplicationInsights.AspNetCore](https://github.com/microsoft/ApplicationInsights-dotnet/blob/main/NETCORE/src/Microsoft.ApplicationInsights.AspNetCore/Implementation/RoleNameContainer.cs)

**Comment by nblumhardt** [comment]
Thanks @meixger! Any chance of a snippet or pseudocode for anyone else who comes upon this?

Pushing the value onto `LogContext` in some ASP.NET Core middleware also seems like it might be an option, if the header name is well-known 🤔

**Comment by meixger** [comment]
The header WAS-DEFAULT-HOSTNAME [seems to be well-known](https://github.com/microsoft/ApplicationInsights-dotnet/issues/1368).

There would be the environment variable WEBSITE_HOSTNAME but it gets not updated when swapping Azure App Service Deployment Slots.

I just get the Cloud Role Name exactly as the internal RoleNameContainer.

[This Gist](https://gist.github.com/meixger/c3f0bb3e4b64a9915ed16692743c5962) shows how i use the internal RoleNameContainer to get and cache the WAS-DEFAULT-HOSTNAME header in a ASP.NET Core middleware and set it in a TraceTelemetryConverter.
