### ISSUE TITLE
RemoteDependency Sinking

### ISSUE THREAD

**Issue by yildizfatih** [serilog-contrib/serilog-sinks-applicationinsights#153]
Is there any way to sink remote dependencies, such as HTTP calls or CosmosDB writes? Do I need to write a custom converter for remote dependency data?

**Comment by Kira-Lappo** [comment]
Any updates? @yildizfatih what was your decision? still using AppInsights packages from MS?

**Comment by nblumhardt** [comment]
Hi! Closing this as stale, but it sounds like an interesting area to investigate, and any suggestions/proposals here would be welcome. Thanks!
