### ISSUE TITLE
application insights issue

### ISSUE THREAD

**Issue by earthcoder** [serilog-contrib/serilog-sinks-applicationinsights#155]
so i added this to my serilog on .net framework and i am using app insights latest version on website but when running the logger i get the following, how can i fix this, sorry my programming skills still learning 

Could not load file or assembly 'Microsoft.ApplicationInsights, Version=2.12.0.21496, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

**Comment by RobBowman** [comment]
Hi @earthcoder , Your project has a reference to the nuget package for Microsoft.ApplicationInsights. It also has a reference to the nuget package for Serilog.Sinks.ApplicationInsights - this also references Microsoft.ApplicationInsights. The versions of Microsoft.ApplicationInsights reference directly from your project and from Serilog.Sinks.ApplicationInsights need to match
