### ISSUE TITLE
Outdated `using-with-azure-functions` section in readme

### ISSUE THREAD

**Issue by rafek1241** [serilog-contrib/serilog-sinks-applicationinsights#167]
Link: https://github.com/serilog/serilog-sinks-applicationinsights#using-with-azure-functions

When i'm trying to use such implementation
![image](https://user-images.githubusercontent.com/9272027/128816887-e6271940-15e8-4741-af64-4e50b73fcfc3.png)

Link for issue: https://docs.microsoft.com/en-us/dotnet/api/Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration.Active?view=azure-dotnet&viewFallbackFrom=netstandard-2.0

**Comment by nblumhardt** [comment]
Thanks for the heads-up! Help with figuring out the correct configuration/a PR for the docs would be very welcome, if anyone's able to.

**Comment by zyofeng** [comment]
I have created a PR with the updated Azure Function setup.

https://github.com/serilog-contrib/serilog-sinks-applicationinsights/pull/191

**Comment by nblumhardt** [comment]
Fixed in #193
