### ISSUE TITLE
Not abe to Use ToDefaultExceptionTelemetry

### ISSUE THREAD

**Issue by puneetkansal97** [serilog-contrib/serilog-sinks-applicationinsights#170]
![image](https://user-images.githubusercontent.com/25348664/131258502-40384f15-cc20-45ff-b4c0-1445a08fc595.png)
![image](https://user-images.githubusercontent.com/25348664/131258513-110b8306-dd2e-425c-b36d-ac490926a0d4.png)

**Comment by puneetkansal97** [comment]
Hi Team, 
This Method was working fine with Serilog verison 2.6.0 but for Using in .Net  core I upgraded to 2.10.0 and Now I am facing above issue

**Comment by nblumhardt** [comment]
Hi! Thanks for the report; if you're able to track this down to a bug in Serilog.Sinks.ApplicationInsights please let us know. Otherwise, unfortunately, we're changing maintenance teams at the moment and don't have the bandwidth to investigate further, sorry.
