### ISSUE TITLE
Question : If my application is offline will the logs saved to some temporary storage and when i go online the logs are uploaded to AppInsight?

### ISSUE THREAD

**Issue by vikramtamboli** [serilog-contrib/serilog-sinks-applicationinsights#173]
Question : If my application is offline will the logs saved to some temporary storage and when i go online the logs are uploaded to Application Insights?

**Comment by nblumhardt** [comment]
No, not with this sink. HTH!

**Comment by klabranche** [comment]
I found a way to have SeriLog w AI work while still having AI temporary storage work when AI can't connect and/or rejects via data limits/rates being hit.

If I configure the WriteTo in appsettings for AI, temp storage breaks.
```
"Serilog": {
"WriteTo": [
      {
        "Name": "ApplicationInsights",
        "Args": {
          "connectionString": "",
          "telemetryConverter": "Serilog.Sinks.ApplicationInsights.TelemetryConverters.TraceTelemetryConverter, Serilog.Sinks.ApplicationInsights",
        }
      }
    ]
}
```

If I don't configure the WriteTo in appsettings for AI, relying on AI appsettings and then add AI in UseSerilog temp storage works for AI.
```
        .UseSerilog((context, services, builder) =>
                builder.ReadFrom.Configuration(context.Configuration)
                .WriteTo.ApplicationInsights(services.GetRequiredService<TelemetryConfiguration>(), TelemetryConverter.Traces)
         )

  "ApplicationInsights": {
    "ConnectionString": "",
    "TempStorage": "folderToRecordTransientAI_LogFailuresTo"
  }
```

**Comment by michele-guion** [comment]
Hello @klabranche, I didn't understand completely your answer.
Did you find a way to get logs even if the app is temporarily offline?
I think that offline storage should be a basic requirement for a sink.
Our app allows users to work also offline. Serilog with this sink works great when online, but we have no logs if something is done offline. I thought that the logs would have been stored somewhere, until the app gets back online, and the logs flushed to AI as soon as there is an available connection. Instead, logs are simply lost.
If this can't be achieved with this sink, is there an alternative? I read all the documentation here and also on Serilog's site, but I couldn't find anything. This seems to be the one and only sink towards AI.
I thank you in advance, I hope you can help me.

Regards
Michele

**Comment by klabranche** [comment]
Yes, the second code/configuration example got us working for the offline data sync.
