### ISSUE TITLE
Question: Is it possible to include data without it rendering in the trace message?

### ISSUE THREAD

**Issue by lucashby** [serilog-contrib/serilog-sinks-applicationinsights#174]
Is there a way to include additional data so that it shows up in 'customDimensions' without being rendered in the message itself?  Is that something I would need to achieve myself, and if so, how would I go about doing that?

**Comment by nblumhardt** [comment]
`Enrich.FromLogContext()` and `LogContext.PushProperty()` should achieve this. HTH!
