### ISSUE TITLE
Serilog logs aren't sent / written into Azure ApplicationInsights for .NET Core API and Worker Service

### ISSUE THREAD

**Issue by florinvirdol** [serilog-contrib/serilog-sinks-applicationinsights#176]
I have a C# ASP .NET Core Web API application and an Worker Service application, but the logs from API and from Worker Service doesn't arrive in Azure Application Insights, can see them only in Console and are written to files.

Both scenario tested: 
- API deployed in Azure AppService + Worker Service deployed as Windows service in Azure in an Windows Server Virtual Machine
- API and Worker Service ran in debug mode from local machine in Visual Studio

Versions:
- .NET 5.0
- Microsoft.ApplicationInsights.AspNetCore 2.18.0 (installed for the API)
- Microsoft.ApplicationInsights.WorkerService 2.18.0 (installed for the Worker Service)
- Serilog 2.10.0
- Serilog.Sinks.ApplicationInsights 3.1.0 (or 2.6.4)

Tried without success even downgrading Serilog.Sinks.ApplicationInsights to version 2.6.4 as suggested in this [issue](https://github.com/serilog/serilog-sinks-applicationinsights/issues/130).

Have both API and Worker service configured the same way:
API - `Program.cs`
```
var options = CommandLineOptions.Configure(args);
await Host.CreateDefaultBuilder(args)
	.ConfigureAppConfiguration(AppConfigurationServices.Configure)
	.ConfigureLogging(LoggerServices.Configure)
	.ConfigureServices(HostServices.Configure)
	.UseSerilog()
	.RunHostAsync(options);

Serilog.Debugging.SelfLog.Enable(msg => Debug.WriteLine(msg));
```

Worker Service - `Program.cs`
```
await Host.CreateDefaultBuilder(args)
	  .ConfigureWebHostDefaults(webBuilder =>
	  {
		  webBuilder
			  .ConfigureAppConfiguration(AppConfigurationServices.Configure)
			  .ConfigureLogging(LoggingServices.Configure)
			  .UseStartup<Startup>();
	  })
	  .UseSerilog()
	  .Build()
	  .RunAsync();

Serilog.Debugging.SelfLog.Enable(msg => Debug.WriteLine(msg));
```

I'm already supplying the Azure App Insights InstrumentationKey in `appSettings.json` two locations:
```
...
"ApplicationInsights": {
    "InstrumentationKey": "xxx-xyz"
  },
...
"Serilog": {
    "Using": [
      "Serilog",
      "Serilog.Sinks.Console",
      "Serilog.Sinks.File",
      "Serilog.Sinks.ApplicationInsights"
    ],
    "MinimumLevel": {
      "Default": "Debug",
      "Override": {
        "Microsoft": "Warning",
        "System": "Warning"
      }
    },
    "WriteTo": [
      {
        "Name": "Console"
      },
      {
        "Name": "File",
        "Args": {
          "path": "Logs/Services-.log",
          "rollingInterval": "Day"
        }
      },
      {
        "Name": "ApplicationInsights",
        "Args": {
          "instrumentationKey": "xxx-xyz",
          "restrictedToMinimumLevel": "Information",
          "telemetryConverter": "Serilog.Sinks.ApplicationInsights.Sinks.ApplicationInsights.TelemetryConverters.TraceTelemetryConverter, Serilog.Sinks.ApplicationInsights"
        }
      }
    ],
    "Enrich": [ "FromLogContext" ]
  }
...
```

When specifying InstrumentationKey only in ApplicationInsights and not under Serilog writer as well, `iKey` wasn't present and i got:
`Application Insights Telemetry (unconfigured) {"name":"AppTraces", "time": "123...", ....}`

After specifying InstrumentationKey in both places (ApplicationInsights and under Serilog writer) you can see multiple records like bellow in the Debug Output window from Visual Studio.
Even enabling Serilog self diagnostic doesn't produce any different output than this one from Debug Output window:
```
Application Insights Telemetry: {"name":"AppRequests", "time": "123...", "iKey": "xxx-xyz", ....}
Application Insights Telemetry: {"name":"AppMetrics", "time": "123...", "iKey": "xxx-xyz", ....}
Application Insights Telemetry: {"name":"AppTraces", "time": "123...", "iKey": "xxx-xyz", ....}
```

**Comment by JGCreator** [comment]
I have this same issue with the Application Insights Sink not configuring properly using `appsettings.json`.

My variation is as follows:
1. no instrumentation key in the sink config (as per documentation suggestion)
2. updated versions
```
  <ItemGroup>
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.20.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="5.0.0" />
    <PackageReference Include="Serilog.Sinks.ApplicationInsights" Version="3.1.0" />
  </ItemGroup>
```

Result:
Trace is sent to app insights for the debug session, but not to Azure.
`Application Insights Telemetry (unconfigured):`

**Comment by wertzui** [comment]
I can confirm the same behavior with my ASP.Net 6 Web API.
When the InstrumentationKey is only present in the ApplicationInsights section in appsettings.json, the trace items are only visible inside Visual Studio while debugging.
After adding the InstrumentationKey to the Args of the ApplicationInsights Sink, they also show up in the Azure portal.

**Comment by DCG-KZ** [comment]
> I can confirm the same behavior with my ASP.Net 6 Web API. When the InstrumentationKey is only present in the ApplicationInsights section in appsettings.json, the trace items are only visible inside Visual Studio while debugging. After adding the InstrumentationKey to the Args of the ApplicationInsights Sink, they also show up in the Azure portal.

How did you manage to send send logs to Insight?

**Comment by wertzui** [comment]
> How did you manage to send logs to Insight?

Add `InstrumentationKey` to the `Args` of the `ApplicationInsights` `WriteTo`-configuration section in appsettings.json, as described in the original issue.

**Comment by wertzui** [comment]
This works for me (replace my-key with your Instrumentation Key)
**appsettings.json**
```
{
  "ApplicationInsights": {
    "InstrumentationKey": "my-key"
  },
  "Serilog": {
    "Using": [
      "Serilog.Sinks.ApplicationInsights"
    ],
    "MinimumLevel": {
      "Default": "Information",
      "Override": {
        "Microsoft": "Warning",
        "System": "Warning"
      }
    },
    "WriteTo": [
      {
        "Name": "Async",
        "Args": {
          "configure": [
            {
              "Name": "Console"
            },
            {
              "Name": "File",
              "restrictedToMinimumLevel": "Information",
              "path": "logs/log.log",
              "rollingInterval": "Day",
              "rollOnFileSizeLimit": true
            }
          ]
        }
      },
      {
        "Name": "ApplicationInsights",
        "Args": {
          "InstrumentationKey": "my-key",
          "restrictedToMinimumLevel": "Information",
          "telemetryConverter": "Serilog.Sinks.ApplicationInsights.Sinks.ApplicationInsights.TelemetryConverters.TraceTelemetryConverter, Serilog.Sinks.ApplicationInsights"
        }
      }
    ],
    "Enrich": [ "FromLogContext" ]
  }
}
```

**Program.cs**
```
public static class Programm
{
        public static void Main(string[] args)
        {
            Log.Logger = new LoggerConfiguration()
                .Enrich.FromLogContext()
                .WriteTo.Console()
                .WriteTo.File("logs/log.log", rollingInterval: RollingInterval.Day, rollOnFileSizeLimit: true)
                .CreateBootstrapLogger();
            try
            {
                Log.Information("Starting up");
                CreateHostBuilder(args).Build().Run();
            }
            catch (Exception e)
            {
                Log.Fatal(e, "Application start-up failed");
            }
            finally
            {
                Log.CloseAndFlush();
            }
        }

        private static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .UseSerilog((context, services, configuration) =>
                    configuration
                        .ReadFrom.Configuration(context.Configuration)
                        .ReadFrom.Services(services)
                        .Enrich.FromLogContext())
                .ConfigureWebHostDefaults(webBuilder => webBuilder.UseStartup<Startup>());
}
```

**Comment by ansaryansu** [comment]
In .Net Core WEB API 6.0, In order to get app insights logs when running locally,  Set "APPINSIGHTS_INSTRUMENTATIONKEY" environment variable in the launch settings.

 "profiles": {
    "ProfileName": {
      "launchBrowser": true,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development",
        "APPINSIGHTS_INSTRUMENTATIONKEY": "your-instrumentation-key"
      }
    }

**Comment by dyardy** [comment]
Does this mean it has to be setup under under both locations

1) 
      {
        "Name": "ApplicationInsights",
        "Args": {
          "instrumentationKey": "xxxxx",
          "telemetryConverter": "Serilog.Sinks.ApplicationInsights.TelemetryConverters.TraceTelemetryConverter, Serilog.Sinks.ApplicationInsights"
        }
      }
      
      and 

2) 
    "profiles": {
    "ProfileName": {
    "launchBrowser": true,
    "environmentVariables": {
    "ASPNETCORE_ENVIRONMENT": "Development",
    "APPINSIGHTS_INSTRUMENTATIONKEY": "your-instrumentation-key"
    }
    }

**Comment by dyardy** [comment]
> Does this mean it has to be setup under under both locations
> 
> 1. {
>    "Name": "ApplicationInsights",
>    "Args": {
>    "instrumentationKey": "xxxxx",
>    "telemetryConverter": "Serilog.Sinks.ApplicationInsights.TelemetryConverters.TraceTelemetryConverter, Serilog.Sinks.ApplicationInsights"
>    }
>    }
>    and
> 2. "profiles": {
>    "ProfileName": {
>    "launchBrowser": true,
>    "environmentVariables": {
>    "ASPNETCORE_ENVIRONMENT": "Development",
>    "APPINSIGHTS_INSTRUMENTATIONKEY": "your-instrumentation-key"
>    }
>    }

I think ONLY #2 is required (above)

**Comment by dyardy** [comment]
I have found I do not need to set environment variable.

Within Serilog appsettings, specify the ConnectionString instead of the Instrumentationkey


      {
        "Name": "ApplicationInsights",
        "Args": {
          //"instrumentationKey": "",
          "ConnectionString": "{provide connection string",
          "telemetryConverter": "Serilog.Sinks.ApplicationInsights.TelemetryConverters.TraceTelemetryConverter, Serilog.Sinks.ApplicationInsights"
        }
      }
