### ISSUE TITLE
A new organization for this repository

### ISSUE THREAD

**Issue by nblumhardt** [serilog-contrib/serilog-sinks-applicationinsights#181]
Hi @serilog/reviewers-application-insights 👋 

Via https://github.com/serilog/serilog/issues/1627 - we're unbundling the `serilog` organization to help distribute the effort involved in managing the various Serilog sub-projects. The `serilog` organization will now only manage the fundamental sinks and other packages that the rest of the ecosystem builds upon.

If this package is actively maintained, it can be moved to a new organization managed by the maintainers. Otherwise, it can move to the `serilog-archive` parking lot, from where we hope a new community-run fork might spring from in the future 🌷 .

Let me know if you're a maintainer and keen to continue this project under a new org; otherwise, I'll shuffle things around and move this one to the archive.

Thanks!

**Comment by joergbattermann** [comment]
@nblumhardt I am no longer actively maintaining, so from my point of view do what you think is best, got my full support / backing there! Thanks!

**Comment by nblumhardt** [comment]
Thanks @joergbattermann 👍 - hope all's going well.

@augustoproiete this sink is very widely used; I know that there are some others out there (and possibly still @aloneguid) interested in pushing development forward - seems like a fit for @serilog-contrib to you?

**Comment by nblumhardt** [comment]
I'm going to move this package to the `serilog-contrib` organization; I'll loop back to this issue with more details of a future maintenance plan as soon as I can.

**Comment by augustoproiete** [comment]
Caught up with @nblumhardt yesterday. `serilog-contrib` is a good move

**Comment by nblumhardt** [comment]
I think the main parts of this move are done; currently, we still need to assemble a larger maintenance team; I'll help figure out a path forward, and I've invited @shahiddev to join. If there's anyone else you can suggest, particularly with a contribution history in this repo, or with a connection to App Insights at Microsoft, let me know. I'll also check out open PRs and see who might be able to lend more of a hand.
