### ISSUE TITLE
Issue with Persistent Channel Use

### ISSUE THREAD

**Issue by johnkattenhorn** [serilog-contrib/serilog-sinks-applicationinsights#19]
I tried to configure Application Insights for Persistent Channels and got an error. I raised this issue with the AppInsight Team https://github.com/Microsoft/ApplicationInsights-dotnet/issues/311 and got a response which suggested I should not be using them in my scenario.

I thought it would be useful to put this here and get some feedback on whether we should change the documentation for the sink.

**Comment by josep1stache** [comment]
Yes, We are having this same error, System.MethodAccessException
Error cuando el método 'Microsoft.ApplicationInsights.Channel.PersistenceChannel..ctor(System.String, Int32)' intentó obtener acceso al método 'Microsoft.ApplicationInsights.Channel.TelemetryBuffer..ctor()'.

**Comment by jbattermann** [comment]
Good evening,

yea that _is_ a bit weird (speaking from the MethodAccessException) and while the question @johnkattenhorn wasn't really answered (why the Exception is happening), it might make sense to update the readme for the sink.

@johnkattenhorn Did you try using the Server Telemetry Channel that was suggested in the AI issue & did it work?

**Comment by johnkattenhorn** [comment]
@jbattermann - Yes I tried it and it works fine.

**Comment by LockTar** [comment]
@johnkattenhorn Maybe good to show your configuration? I now installed the other Nuget package and used this configuration
`var configuration = new TelemetryConfiguration()
            {
                InstrumentationKey = applicationInsightsInstrumentationKey,
                TelemetryChannel = new ServerTelemetryChannel()
            };`

**Comment by lorenzogiudici5** [comment]
Talking about Server Telemetry Channel, @jbattermann, I am trying to use it in my winform application, but I am having some problems: when the application runs offline, no tracks are sent in AI :(
I configured the Channel following [this](http://apmtips.com/blog/2016/01/31/telemetry-channels-update/) article

**Comment by sahithi77** [comment]
Even im facing same problem @lorenzogiudici5 :(

**Comment by marquesh** [comment]
I'm facing the same problem here.

Using a Server Telemetry Channel in my configuration, if my application is running offline, no trace is sent to AI when the network connection is back again.

I tried to find out where those logs are stored and @ AppData\Local\Microsoft\ApplicationInsights i see a folder that is modified each time, but there's nothing inside. 

Any help ?

**Comment by aloneguid** [comment]
It looks like persistent channels are not supported anymore by AI (see discussion in #81). The official MS recommendation is to implement your own. I'm not quite following this decision to be honest, but that's what it is.

I'm thinking of building an alternative persistent channel implementation that will work across different .net runtimes. What is your scenario by the way, is it desktop, console app or something else?

**Comment by marquesh** [comment]
Thanks for your quick reply !
Ok, I'll let you know if i advance on my side.

I was trying to use it in a windows console/service that runs in the windows background for a user.

**Comment by nblumhardt** [comment]
Closing as stale.
