### ISSUE TITLE
Add Configuration in Readme

### ISSUE THREAD

**Issue by ranouf** [serilog-contrib/serilog-sinks-applicationinsights#52]
Hi,

I found the configuration for AppSettings in the Issues:
```
	{
		"Serilog": {
			[...]
			"WriteTo": [
				[...]
				{
					"Name": "ApplicationInsightsEvents",
					"Args": { "instrumentationKey": "<MyApplicationInsightsInstrumentationKey>" }
				}
			],
			[...]
		}
	},
```

It could be interesting to write it in the git Readme to be sure that the next one like me will find it. Moreover other Serilog Github package shows their configuration too.

Thanks

**Comment by tomkerkhove** [comment]
This seems to be added so the issue can be closed, right @aloneguid?

https://github.com/serilog/serilog-sinks-applicationinsights#configuring-with-readfromconfiguration
