### ISSUE TITLE
Optionally log Context properties as JSON intead of "dotting out"

### ISSUE THREAD

**Issue by zippy1981** [serilog-contrib/serilog-sinks-applicationinsights#59]
The was [ApplicationInsightsPropertyFormatter](https://github.com/serilog/serilog-sinks-applicationinsights/blob/master/src/Serilog.Sinks.ApplicationInsights/Sinks/ApplicationInsights/ApplicationInsightsPropertyFormatter.cs) works now is ok for simple PODOs. Its terrible for arrays. Regardless, in many instances you'd probably want to just JSON serialize PODOs that were properties pushed to `LogContext`.

That is unless PowerBI or whatever else people used besides the web porta for Application Insights deserialized that dot notation automatically.

**Comment by mjpearse** [comment]
Yeah similar request.  
We are having to serialise properties like this to a json string and then on the other side use parsejson in Application Insights analytics queries to workaround this and get data out to Power BI.  

It messes with our logs in other sinks however so avoid doing this where we can.  Basically our logs that contained arrays were growing inexorably large in AI and not usable by tools like Power BI....

**Comment by aloneguid** [comment]
It seems like we can do this with `JsonValueFormatter`, already looking into it. 

https://nblumhardt.com/2016/07/serilog-2-0-json-improvements/

**Comment by aloneguid** [comment]
@mjpearse fixed in v3 release, please reopen if any issues ;)
