### ISSUE TITLE
Use with Application Insights - Traces or Events

### ISSUE THREAD

**Issue by larserikfinholt** [serilog-contrib/serilog-sinks-applicationinsights#63]
We're using dotnet core 2.1, and it seems like serilog is modifing the request sent to Application Insigths. 

Is it possible to use the default behavior of Application Insights, and Serilog together? As it is now (maybe I get it wrong) we need to send all telemetry to either  ApplicationInsightsTraces or ApplicationInsightsEvents.

In the azure portal (AI blade) a request are listed as a traces or a custom event.

**Comment by tomkerkhove** [comment]
Would it make sense to allow us to configure that we want to use AI-based request tracking and we provide the template in which you can parse it?

For example, [`serilog-aspnetcore`'s Request logging](https://github.com/serilog/serilog-aspnetcore#request-logging-300-) uses the `HTTP {RequestMethod} {RequestPath} responded {StatusCode} in {Elapsed:0.0000} ms` format which can be used, or do you need more information.

Sounds a bit messy but would actually make sense and be a wonderful feature. The reason why I would love this is to make it more explicit that this is a request in application insights so I don't have to plow through the traces.

On the note of ASP.NET, the default is a bit chatty in my opinion and I'm actually looking to disable that in favor of something like the request logging and tweak that a bit more.

**Comment by nblumhardt** [comment]
Closing this one as stale, but sounds like an interesting area for investigation if anyone's keen on exploring further/creating a proposal? Let me know if so 👍
