### ISSUE TITLE
Add ApplicationInsights Details through XML Configuration

### ISSUE THREAD

**Issue by laxman4434** [serilog-contrib/serilog-sinks-applicationinsights#69]
How to set the key when using Serilog.Settings.appsettings

Tried this way :
```
<add key="serilog:using:ApplicationInsights" value="Serilog.Sinks.ApplicationInsights" />
<add key="serilog:write-to:ApplicationInsightsEvents" value="<my key value>" />
```

But that doesn't work.

Any help would be appreciated.

**Comment by joaopgrassi** [comment]
You can specify the properties on the `ApplicationInsightsEvents()` constructor also in the xml file. If you check, one of the overloads accepts a `instrumentationKey` parameter. So, you can do this:

```
<add key="serilog:using:ApplicationInsights" value="Serilog.Sinks.ApplicationInsights" />
<add key="serilog:write-to:ApplicationInsightsEvents.instrumentationKey" value="d89a4f1d-e3f8-4c22-ba34-2fee8cb4dd4f" />
```

Every parameter on the constructor can be added that way.

**Comment by joaopgrassi** [comment]
You can specify the properties on the `ApplicationInsightsEvents()` constructor also in the xml file. If you check, one of the overloads accepts a `instrumentationKey` parameter. So, you can do this:

```
<add key="serilog:using:ApplicationInsights" value="Serilog.Sinks.ApplicationInsights" />
<add key="serilog:write-to:ApplicationInsightsEvents.instrumentationKey" value="your key" />
```
Every parameter on the constructor can be added that way.
